In [11]:
import pandas as pd

try:
    df_raw = pd.read_csv('Actual Spend DataPrep.csv')
    display(df_raw.head())
    print(df_raw.shape)
except FileNotFoundError:
    print("Error: 'Actual Spend DataPrep.csv' not found.")
    df_raw = None
except pd.errors.ParserError:
    print("Error: Unable to parse the CSV file.")
    df_raw = None
except Exception as e:
    print(f"An unexpected error occurred: {e}")
    df_raw = None

,AWS A/c No,New A/c name,Owner,Apr-24,May-24,Jun-24,Jul-24,Aug-24,Sep-24,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25
0,072401294672,DMS AWS,Abhinav Gupta,9.4 K,9.2 K,9.5 K,9.6 K,9.6 K,15.0 K,12.2 K,9.5 K,9.7 K,9.9 K,10.1 K,10.3 K
1,901553615594,merchantdashboards,Abhinav Gupta,58.7 K,54.6 K,51.5 K,49.4 K,47.3 K,46.8 K,49.5 K,49.1 K,50.1 K,51.1 K,52.1 K,53.2 K
2,480732456233,dms-prod_ocl,Abhinav Gupta,6.8 K,6.7 K,6.7 K,6.9 K,7.5 K,7.6 K,7.0 K,6.6 K,6.7 K,6.8 K,7.0 K,7.1 K
3,182401677120,onboardingengine,Abhinav Gupta,27.8 K,28.0 K,27.1 K,27.6 K,27.7 K,27.5 K,26.3 K,26.2 K,26.7 K,27.2 K,27.8 K,28.3 K
4,389881277731,merchant-business,Abhinav Gupta,1.0 K,0.8 K,0.8 K,0.8 K,0.8 K,0.8 K,0.8 K,0.8 K,0.8 K,0.8 K,0.8 K,0.9 K

(219, 15)

In [12]:
# prompt: update the amount value in Months columns like Apr-24 to Mar-25. the amount is mentioned with K at the end where K means 1000 so multiply each value with 1000 and show the exact value in each column.

import pandas as pd

try:
    df_raw = pd.read_csv('Actual Spend DataPrep.csv')
    #display(df_raw.head())
    #print(df_raw.shape)

    # Assuming your months columns are 'Apr-24', 'May-24', etc.
    # Replace with actual column names if they are different

    months = ['Apr-24', 'May-24', 'Jun-24', 'Jul-24', 'Aug-24', 'Sep-24', 'Oct-24', 'Nov-24', 'Dec-24', 'Jan-25', 'Feb-25', 'Mar-25']

    for month in months:
        if month in df_raw.columns:
            df_raw[month] = df_raw[month].astype(str).str.replace('K', '', regex=False)
            df_raw[month] = pd.to_numeric(df_raw[month], errors='coerce')
            df_raw[month] = df_raw[month] * 1000
            df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
            df_raw[month] = df_raw[month].astype(int) # Convert to integer type after filling null

    display(df_raw.head())

except FileNotFoundError:
    print("Error: 'Actual Spend DataPrep.csv' not found.")
except pd.errors.ParserError:
    print("Error: Unable to parse the CSV file.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0
<ipython-input-12-bee1deec0ae5>:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_raw[month].fillna(0, inplace=True) # Replace any non-numeric values with 0

,AWS A/c No,New A/c name,Owner,Apr-24,May-24,Jun-24,Jul-24,Aug-24,Sep-24,Oct-24,Nov-24,Dec-24,Jan-25,Feb-25,Mar-25
0,072401294672,DMS AWS,Abhinav Gupta,9400,9200,9500,9600,9600,15000,12200,9500,9700,9900,10100,10300
1,901553615594,merchantdashboards,Abhinav Gupta,58700,54600,51500,49400,47300,46800,49500,49100,50100,51100,52100,53200
2,480732456233,dms-prod_ocl,Abhinav Gupta,6800,6700,6700,6900,7500,7600,7000,6600,6700,6800,7000,7100
3,182401677120,onboardingengine,Abhinav Gupta,27800,28000,27100,27600,27700,27500,26300,26200,26700,27200,27800,28300
4,389881277731,merchant-business,Abhinav Gupta,1000,800,800,800,800,800,800,800,800,800,800,900

In [13]:
# prompt: transpose all rows of month columns into rows under a new date column with value of "Apr-24" being changed as date of the start of the month as "01-Apr-2024" and so on for all column months.

import pandas as pd

try:

    # Assuming your months columns are 'Apr-24', 'May-24', etc.
    # Replace with actual column names if they are different
    months = ['Apr-24', 'May-24', 'Jun-24', 'Jul-24', 'Aug-24', 'Sep-24', 'Oct-24', 'Nov-24', 'Dec-24', 'Jan-25', 'Feb-25', 'Mar-25']

    # Create a new list to store the modified month names
    new_months = []
    for month in months:
        if month in df_raw.columns:
            parts = month.split('-')
            day = "01"
            year = "20" + parts[1] if int(parts[1]) >= 0 and int(parts[1]) <= 99 else parts[1] # Handle years like 2024
            new_month = f"{day}-{parts[0]}-{year}"
            new_months.append(new_month)

    # Initialize an empty list to store the transposed data
    transposed_data = []

    # Iterate through the rows of the original DataFrame
    for index, row in df_raw.iterrows():
        for i, month in enumerate(months):
            if month in df_raw.columns:
                new_row = {
                    'Date': new_months[i],
                    'Value': row[month]
                }
                #Add other columns from the original row
                for col in df_raw.columns:
                  if col not in months:
                    new_row[col] = row[col]
                transposed_data.append(new_row)

    # Create the new DataFrame from the transposed data
    df_transposed = pd.DataFrame(transposed_data)

    display(df_transposed.head())
    print(df_transposed.shape)


except FileNotFoundError:
    print("Error: 'Actual Spend DataPrep.csv' not found.")
except pd.errors.ParserError:
    print("Error: Unable to parse the CSV file.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

          Date  Value    AWS A/c No New A/c name          Owner
0  01-Apr-2024   9400  072401294672      DMS AWS  Abhinav Gupta
1  01-May-2024   9200  072401294672      DMS AWS  Abhinav Gupta
2  01-Jun-2024   9500  072401294672      DMS AWS  Abhinav Gupta
3  01-Jul-2024   9600  072401294672      DMS AWS  Abhinav Gupta
4  01-Aug-2024   9600  072401294672      DMS AWS  Abhinav Gupta

(2628, 5)

In [14]:
# prompt: rename and reorder columns as account_id TEXT NOT NULL, date DATE NOT NULL, spend REAL NOT NULL, resource_type TEXT with default value as "compute". The current column names are, "Date	Value	AWS A/c No	New A/c name	Owner"

import pandas as pd
try:
    # ... (Your existing code)

    # Rename and reorder columns
    df_transposed = df_transposed.rename(columns={
        'AWS A/c No': 'account_id',
        'Date': 'date',
        'Value': 'spend'
    })

    df_transposed = df_transposed[['account_id', 'date', 'spend', 'New A/c name', 'Owner']]

    # Ensure 'account_id' is of type TEXT and NOT NULL (replace with appropriate handling if needed)
    df_transposed['account_id'] = df_transposed['account_id'].astype(str)  # Convert to string type
    # Note:  Directly enforcing NOT NULL is not possible in pandas.  You'd typically handle this during database loading

    # Ensure 'date' is of type DATE (replace with appropriate date conversion if needed)
    df_transposed['date'] = pd.to_datetime(df_transposed['date'], errors='coerce') #Try to convert to date, invalid dates become NaT
    df_transposed['date'] = df_transposed['date'].dt.strftime('%Y-%m-%d') #Format the date to YYYY-MM-DD


    # Ensure 'spend' is of type REAL (float) and NOT NULL (replace with appropriate handling if needed)
    df_transposed['spend'] = pd.to_numeric(df_transposed['spend'], errors='coerce') #Coerce to numeric, non-numeric becomes NaN
    df_transposed['spend'] = df_transposed['spend'].astype(float) #Convert to float

    # Add 'resource_type' column with default value "compute"
    df_transposed['resource_type'] = 'compute'

    display(df_transposed.head())
    print(df_transposed.shape)


except FileNotFoundError:
    print("Error: 'Actual Spend DataPrep.csv' not found.")
except pd.errors.ParserError:
    print("Error: Unable to parse the CSV file.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

     account_id        date   spend New A/c name          Owner resource_type
0  072401294672  2024-04-01  9400.0      DMS AWS  Abhinav Gupta       compute
1  072401294672  2024-05-01  9200.0      DMS AWS  Abhinav Gupta       compute
2  072401294672  2024-06-01  9500.0      DMS AWS  Abhinav Gupta       compute
3  072401294672  2024-07-01  9600.0      DMS AWS  Abhinav Gupta       compute
4  072401294672  2024-08-01  9600.0      DMS AWS  Abhinav Gupta       compute

(2628, 6)

In [15]:
# prompt: drop the column "New A/c name" and "Owner". and reorder rest of the column as "account_id,date,spend,resource_type"

# Drop columns
df_transposed = df_transposed.drop(columns=['New A/c name', 'Owner'], errors='ignore')

# Reorder columns
df_transposed = df_transposed[['account_id', 'date', 'spend', 'resource_type']]

display(df_transposed.head())
df_transposed.shape

     account_id        date   spend resource_type
0  072401294672  2024-04-01  9400.0       compute
1  072401294672  2024-05-01  9200.0       compute
2  072401294672  2024-06-01  9500.0       compute
3  072401294672  2024-07-01  9600.0       compute
4  072401294672  2024-08-01  9600.0       compute

(2628, 4)

In [17]:
# prompt: save the dataframe to csv

try:
    df_transposed.to_csv('actual_spend.csv', index=False)
    print("DataFrame saved to actual_spend.csv")
except Exception as e:
    print(f"An error occurred while saving the DataFrame: {e}")

DataFrame saved to actual_spend.csv